site_name: Documentación método Rk4

theme:
  name: "material"
  palette:
    primary: teal
    scheme: slate
    accent: cyan

nav:
  - index.md
  - reference.md
  - explanation.md
  - tutorials.md

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
